/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const DebtPayment = IDL.Record({
  'amountPaid' : IDL.Nat,
  'remainingBalance' : IDL.Nat,
  'paymentDate' : Time,
});
export const DebtStatus = IDL.Variant({
  'active' : IDL.Null,
  'overdue' : IDL.Nat,
  'paidOff' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'resource' : ExternalBlob,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'resourceType' : IDL.Text,
});
export const WellnessPillar = IDL.Record({
  'name' : IDL.Text,
  'progress' : IDL.Nat,
});
export const QuizResponse = IDL.Record({
  'answer' : IDL.Text,
  'questionId' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'content' : IDL.Text,
  'timestamp' : Time,
});
export const Badge = IDL.Record({
  'achieved' : IDL.Bool,
  'achievedTimestamp' : IDL.Opt(Time),
  'name' : IDL.Text,
  'pointsNeeded' : IDL.Nat,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
});
export const MindfulnessActivity = IDL.Record({
  'duration' : IDL.Nat,
  'activityType' : IDL.Text,
  'timestamp' : Time,
});
export const MedicationAdherence = IDL.Record({
  'taken' : IDL.Bool,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const MedicationRecord = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Opt(Time),
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'adherenceLogs' : IDL.Vec(MedicationAdherence),
  'frequency' : IDL.Text,
  'timeOfDay' : IDL.Text,
  'startDate' : Time,
});
export const Reward = IDL.Record({
  'source' : IDL.Text,
  'description' : IDL.Text,
  'rewardType' : IDL.Text,
  'timestamp' : Time,
});
export const DebtRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : DebtStatus,
  'payments' : IDL.Vec(DebtPayment),
  'dueDate' : Time,
  'interestRate' : IDL.Nat,
  'creditorName' : IDL.Text,
  'amount' : IDL.Nat,
});
export const WellnessMetrics = IDL.Record({
  'social' : IDL.Nat,
  'spiritual' : IDL.Nat,
  'personal' : IDL.Nat,
  'leisure' : IDL.Nat,
  'emotional' : IDL.Nat,
  'financial' : IDL.Nat,
  'physical' : IDL.Nat,
});
export const ProgressPhoto = IDL.Record({
  'description' : IDL.Text,
  'isBaseline' : IDL.Bool,
  'timestamp' : Time,
  'photo' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'usageDurationMonths' : IDL.Nat,
  'quizResponses' : IDL.Vec(QuizResponse),
  'username' : IDL.Text,
  'journalEntries' : IDL.Vec(JournalEntry),
  'badges' : IDL.Vec(Badge),
  'wellnessPillars' : IDL.Vec(WellnessPillar),
  'email' : IDL.Text,
  'mindfulnessActivities' : IDL.Vec(MindfulnessActivity),
  'medications' : IDL.Vec(MedicationRecord),
  'onboardingCompleted' : IDL.Bool,
  'gamifiedScore' : IDL.Nat,
  'rewards' : IDL.Vec(Reward),
  'skinHealthScore' : IDL.Nat,
  'debts' : IDL.Vec(DebtRecord),
  'wellnessMetrics' : WellnessMetrics,
  'points' : IDL.Nat,
  'progressPhotos' : IDL.Vec(ProgressPhoto),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDebt' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Vec(DebtPayment), DebtStatus],
      [],
      [],
    ),
  'addDebtPayment' : IDL.Func([IDL.Nat, DebtPayment], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text], [], []),
  'addMedication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time)],
      [],
      [],
    ),
  'addMindfulnessActivity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeOnboarding' : IDL.Func([], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteDebt' : IDL.Func([IDL.Nat], [], []),
  'deleteMedication' : IDL.Func([IDL.Nat], [], []),
  'deleteResource' : IDL.Func([IDL.Nat], [], []),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAllUserWellnessPillars' : IDL.Func(
      [],
      [IDL.Vec(WellnessPillar)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
  'getBaselinePhoto' : IDL.Func([], [IDL.Opt(ProgressPhoto)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDebts' : IDL.Func([], [IDL.Vec(DebtRecord)], ['query']),
  'getFollowupPhoto' : IDL.Func([], [IDL.Opt(ProgressPhoto)], ['query']),
  'getMedications' : IDL.Func([], [IDL.Vec(MedicationRecord)], ['query']),
  'getPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getProgressPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
  'getResourceById' : IDL.Func([IDL.Nat], [IDL.Opt(Resource)], ['query']),
  'getResourcesByType' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getUsageDuration' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWellnessMetrics' : IDL.Func([], [WellnessMetrics], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnboardingCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'logMedicationAdherence' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
  'manageRewards' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveQuizResponse' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'searchResources' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
  'setUsageDuration' : IDL.Func([IDL.Nat], [], []),
  'updateDebt' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        Time,
        IDL.Vec(DebtPayment),
        DebtStatus,
      ],
      [],
      [],
    ),
  'updateDebtStatus' : IDL.Func([IDL.Nat, DebtStatus], [], []),
  'updateMedication' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time)],
      [],
      [],
    ),
  'updateResource' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'updateWellnessPillar' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'uploadProgressPhoto' : IDL.Func([ExternalBlob, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const DebtPayment = IDL.Record({
    'amountPaid' : IDL.Nat,
    'remainingBalance' : IDL.Nat,
    'paymentDate' : Time,
  });
  const DebtStatus = IDL.Variant({
    'active' : IDL.Null,
    'overdue' : IDL.Nat,
    'paidOff' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'resource' : ExternalBlob,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'resourceType' : IDL.Text,
  });
  const WellnessPillar = IDL.Record({
    'name' : IDL.Text,
    'progress' : IDL.Nat,
  });
  const QuizResponse = IDL.Record({
    'answer' : IDL.Text,
    'questionId' : IDL.Text,
  });
  const JournalEntry = IDL.Record({ 'content' : IDL.Text, 'timestamp' : Time });
  const Badge = IDL.Record({
    'achieved' : IDL.Bool,
    'achievedTimestamp' : IDL.Opt(Time),
    'name' : IDL.Text,
    'pointsNeeded' : IDL.Nat,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
  });
  const MindfulnessActivity = IDL.Record({
    'duration' : IDL.Nat,
    'activityType' : IDL.Text,
    'timestamp' : Time,
  });
  const MedicationAdherence = IDL.Record({
    'taken' : IDL.Bool,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const MedicationRecord = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Opt(Time),
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'adherenceLogs' : IDL.Vec(MedicationAdherence),
    'frequency' : IDL.Text,
    'timeOfDay' : IDL.Text,
    'startDate' : Time,
  });
  const Reward = IDL.Record({
    'source' : IDL.Text,
    'description' : IDL.Text,
    'rewardType' : IDL.Text,
    'timestamp' : Time,
  });
  const DebtRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : DebtStatus,
    'payments' : IDL.Vec(DebtPayment),
    'dueDate' : Time,
    'interestRate' : IDL.Nat,
    'creditorName' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const WellnessMetrics = IDL.Record({
    'social' : IDL.Nat,
    'spiritual' : IDL.Nat,
    'personal' : IDL.Nat,
    'leisure' : IDL.Nat,
    'emotional' : IDL.Nat,
    'financial' : IDL.Nat,
    'physical' : IDL.Nat,
  });
  const ProgressPhoto = IDL.Record({
    'description' : IDL.Text,
    'isBaseline' : IDL.Bool,
    'timestamp' : Time,
    'photo' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'usageDurationMonths' : IDL.Nat,
    'quizResponses' : IDL.Vec(QuizResponse),
    'username' : IDL.Text,
    'journalEntries' : IDL.Vec(JournalEntry),
    'badges' : IDL.Vec(Badge),
    'wellnessPillars' : IDL.Vec(WellnessPillar),
    'email' : IDL.Text,
    'mindfulnessActivities' : IDL.Vec(MindfulnessActivity),
    'medications' : IDL.Vec(MedicationRecord),
    'onboardingCompleted' : IDL.Bool,
    'gamifiedScore' : IDL.Nat,
    'rewards' : IDL.Vec(Reward),
    'skinHealthScore' : IDL.Nat,
    'debts' : IDL.Vec(DebtRecord),
    'wellnessMetrics' : WellnessMetrics,
    'points' : IDL.Nat,
    'progressPhotos' : IDL.Vec(ProgressPhoto),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDebt' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Vec(DebtPayment), DebtStatus],
        [],
        [],
      ),
    'addDebtPayment' : IDL.Func([IDL.Nat, DebtPayment], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text], [], []),
    'addMedication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time)],
        [],
        [],
      ),
    'addMindfulnessActivity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeOnboarding' : IDL.Func([], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteDebt' : IDL.Func([IDL.Nat], [], []),
    'deleteMedication' : IDL.Func([IDL.Nat], [], []),
    'deleteResource' : IDL.Func([IDL.Nat], [], []),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAllUserWellnessPillars' : IDL.Func(
        [],
        [IDL.Vec(WellnessPillar)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBadges' : IDL.Func([], [IDL.Vec(Badge)], ['query']),
    'getBaselinePhoto' : IDL.Func([], [IDL.Opt(ProgressPhoto)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDebts' : IDL.Func([], [IDL.Vec(DebtRecord)], ['query']),
    'getFollowupPhoto' : IDL.Func([], [IDL.Opt(ProgressPhoto)], ['query']),
    'getMedications' : IDL.Func([], [IDL.Vec(MedicationRecord)], ['query']),
    'getPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getProgressPhotos' : IDL.Func([], [IDL.Vec(ProgressPhoto)], ['query']),
    'getResourceById' : IDL.Func([IDL.Nat], [IDL.Opt(Resource)], ['query']),
    'getResourcesByType' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getUsageDuration' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWellnessMetrics' : IDL.Func([], [WellnessMetrics], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnboardingCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'logMedicationAdherence' : IDL.Func([IDL.Nat, IDL.Bool, IDL.Text], [], []),
    'manageRewards' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveQuizResponse' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'searchResources' : IDL.Func([IDL.Text], [IDL.Vec(Resource)], ['query']),
    'setUsageDuration' : IDL.Func([IDL.Nat], [], []),
    'updateDebt' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          Time,
          IDL.Vec(DebtPayment),
          DebtStatus,
        ],
        [],
        [],
      ),
    'updateDebtStatus' : IDL.Func([IDL.Nat, DebtStatus], [], []),
    'updateMedication' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Opt(Time)],
        [],
        [],
      ),
    'updateResource' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'updateWellnessPillar' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'uploadProgressPhoto' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };