/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Badge {
  'achieved' : boolean,
  'achievedTimestamp' : [] | [Time],
  'name' : string,
  'pointsNeeded' : bigint,
  'description' : string,
  'progress' : bigint,
}
export interface DebtPayment {
  'amountPaid' : bigint,
  'remainingBalance' : bigint,
  'paymentDate' : Time,
}
export interface DebtRecord {
  'id' : bigint,
  'status' : DebtStatus,
  'payments' : Array<DebtPayment>,
  'dueDate' : Time,
  'interestRate' : bigint,
  'creditorName' : string,
  'amount' : bigint,
}
export type DebtStatus = { 'active' : null } |
  { 'overdue' : bigint } |
  { 'paidOff' : null };
export type ExternalBlob = Uint8Array;
export interface JournalEntry { 'content' : string, 'timestamp' : Time }
export interface MedicationAdherence {
  'taken' : boolean,
  'notes' : string,
  'timestamp' : Time,
}
export interface MedicationRecord {
  'id' : bigint,
  'endDate' : [] | [Time],
  'dosage' : string,
  'name' : string,
  'adherenceLogs' : Array<MedicationAdherence>,
  'frequency' : string,
  'timeOfDay' : string,
  'startDate' : Time,
}
export interface MindfulnessActivity {
  'duration' : bigint,
  'activityType' : string,
  'timestamp' : Time,
}
export interface ProgressPhoto {
  'description' : string,
  'isBaseline' : boolean,
  'timestamp' : Time,
  'photo' : ExternalBlob,
}
export interface QuizResponse { 'answer' : string, 'questionId' : string }
export interface Resource {
  'id' : bigint,
  'title' : string,
  'resource' : ExternalBlob,
  'link' : string,
  'description' : string,
  'resourceType' : string,
}
export interface Reward {
  'source' : string,
  'description' : string,
  'rewardType' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'usageDurationMonths' : bigint,
  'quizResponses' : Array<QuizResponse>,
  'username' : string,
  'journalEntries' : Array<JournalEntry>,
  'badges' : Array<Badge>,
  'wellnessPillars' : Array<WellnessPillar>,
  'email' : string,
  'mindfulnessActivities' : Array<MindfulnessActivity>,
  'medications' : Array<MedicationRecord>,
  'onboardingCompleted' : boolean,
  'gamifiedScore' : bigint,
  'rewards' : Array<Reward>,
  'skinHealthScore' : bigint,
  'debts' : Array<DebtRecord>,
  'wellnessMetrics' : WellnessMetrics,
  'points' : bigint,
  'progressPhotos' : Array<ProgressPhoto>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessMetrics {
  'social' : bigint,
  'spiritual' : bigint,
  'personal' : bigint,
  'leisure' : bigint,
  'emotional' : bigint,
  'financial' : bigint,
  'physical' : bigint,
}
export interface WellnessPillar { 'name' : string, 'progress' : bigint }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDebt' : ActorMethod<
    [string, bigint, bigint, Time, Array<DebtPayment>, DebtStatus],
    undefined
  >,
  'addDebtPayment' : ActorMethod<[bigint, DebtPayment], undefined>,
  'addJournalEntry' : ActorMethod<[string], undefined>,
  'addMedication' : ActorMethod<
    [string, string, string, string, Time, [] | [Time]],
    undefined
  >,
  'addMindfulnessActivity' : ActorMethod<[string, bigint], undefined>,
  'addResource' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeOnboarding' : ActorMethod<[], undefined>,
  'createUserProfile' : ActorMethod<[string, string], undefined>,
  'deleteDebt' : ActorMethod<[bigint], undefined>,
  'deleteMedication' : ActorMethod<[bigint], undefined>,
  'deleteResource' : ActorMethod<[bigint], undefined>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAllUserWellnessPillars' : ActorMethod<[], Array<WellnessPillar>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getBadges' : ActorMethod<[], Array<Badge>>,
  'getBaselinePhoto' : ActorMethod<[], [] | [ProgressPhoto]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDebts' : ActorMethod<[], Array<DebtRecord>>,
  'getFollowupPhoto' : ActorMethod<[], [] | [ProgressPhoto]>,
  'getMedications' : ActorMethod<[], Array<MedicationRecord>>,
  'getPoints' : ActorMethod<[], bigint>,
  'getProgressPhotos' : ActorMethod<[], Array<ProgressPhoto>>,
  'getResourceById' : ActorMethod<[bigint], [] | [Resource]>,
  'getResourcesByType' : ActorMethod<[string], Array<Resource>>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getUsageDuration' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWellnessMetrics' : ActorMethod<[], WellnessMetrics>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnboardingCompleted' : ActorMethod<[], boolean>,
  'logMedicationAdherence' : ActorMethod<[bigint, boolean, string], undefined>,
  'manageRewards' : ActorMethod<
    [string, bigint, bigint, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveQuizResponse' : ActorMethod<[string, string], undefined>,
  'searchResources' : ActorMethod<[string], Array<Resource>>,
  'setUsageDuration' : ActorMethod<[bigint], undefined>,
  'updateDebt' : ActorMethod<
    [bigint, string, bigint, bigint, Time, Array<DebtPayment>, DebtStatus],
    undefined
  >,
  'updateDebtStatus' : ActorMethod<[bigint, DebtStatus], undefined>,
  'updateMedication' : ActorMethod<
    [bigint, string, string, string, string, Time, [] | [Time]],
    undefined
  >,
  'updateResource' : ActorMethod<
    [bigint, string, string, string, string, ExternalBlob],
    undefined
  >,
  'updateWellnessPillar' : ActorMethod<[string, bigint], undefined>,
  'uploadProgressPhoto' : ActorMethod<
    [ExternalBlob, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];