/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WellnessMetrics {
    social: bigint;
    spiritual: bigint;
    personal: bigint;
    leisure: bigint;
    emotional: bigint;
    financial: bigint;
    physical: bigint;
}
export interface MedicationAdherence {
    taken: boolean;
    notes: string;
    timestamp: Time;
}
export type Time = bigint;
export interface Reward {
    source: string;
    description: string;
    rewardType: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MindfulnessActivity {
    duration: bigint;
    activityType: string;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DebtRecord {
    id: bigint;
    status: DebtStatus;
    payments: Array<DebtPayment>;
    dueDate: Time;
    interestRate: bigint;
    creditorName: string;
    amount: bigint;
}
export interface MedicationRecord {
    id: bigint;
    endDate?: Time;
    dosage: string;
    name: string;
    adherenceLogs: Array<MedicationAdherence>;
    frequency: string;
    timeOfDay: string;
    startDate: Time;
}
export type DebtStatus = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "overdue";
    overdue: bigint;
} | {
    __kind__: "paidOff";
    paidOff: null;
};
export interface QuizResponse {
    answer: string;
    questionId: string;
}
export interface DebtPayment {
    amountPaid: bigint;
    remainingBalance: bigint;
    paymentDate: Time;
}
export interface Badge {
    achieved: boolean;
    achievedTimestamp?: Time;
    name: string;
    pointsNeeded: bigint;
    description: string;
    progress: bigint;
}
export interface WellnessPillar {
    name: string;
    progress: bigint;
}
export interface JournalEntry {
    content: string;
    timestamp: Time;
}
export interface Resource {
    id: bigint;
    title: string;
    resource: ExternalBlob;
    link: string;
    description: string;
    resourceType: string;
}
export interface ProgressPhoto {
    description: string;
    isBaseline: boolean;
    timestamp: Time;
    photo: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    id: Principal;
    usageDurationMonths: bigint;
    quizResponses: Array<QuizResponse>;
    username: string;
    journalEntries: Array<JournalEntry>;
    badges: Array<Badge>;
    wellnessPillars: Array<WellnessPillar>;
    email: string;
    mindfulnessActivities: Array<MindfulnessActivity>;
    medications: Array<MedicationRecord>;
    onboardingCompleted: boolean;
    gamifiedScore: bigint;
    rewards: Array<Reward>;
    skinHealthScore: bigint;
    debts: Array<DebtRecord>;
    wellnessMetrics: WellnessMetrics;
    points: bigint;
    progressPhotos: Array<ProgressPhoto>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDebt(creditorName: string, amount: bigint, interestRate: bigint, dueDate: Time, payments: Array<DebtPayment>, status: DebtStatus): Promise<void>;
    addDebtPayment(debtId: bigint, payment: DebtPayment): Promise<void>;
    addJournalEntry(content: string): Promise<void>;
    addMedication(name: string, dosage: string, frequency: string, timeOfDay: string, startDate: Time, endDate: Time | null): Promise<void>;
    addMindfulnessActivity(activityType: string, duration: bigint): Promise<void>;
    addResource(title: string, description: string, resourceType: string, link: string, resource: ExternalBlob): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeOnboarding(): Promise<void>;
    createUserProfile(email: string, username: string): Promise<void>;
    deleteDebt(debtId: bigint): Promise<void>;
    deleteMedication(medicationId: bigint): Promise<void>;
    deleteResource(id: bigint): Promise<void>;
    getAllResources(): Promise<Array<Resource>>;
    getAllUserWellnessPillars(): Promise<Array<WellnessPillar>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getBadges(): Promise<Array<Badge>>;
    getBaselinePhoto(): Promise<ProgressPhoto | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDebts(): Promise<Array<DebtRecord>>;
    getFollowupPhoto(): Promise<ProgressPhoto | null>;
    getMedications(): Promise<Array<MedicationRecord>>;
    getPoints(): Promise<bigint>;
    getProgressPhotos(): Promise<Array<ProgressPhoto>>;
    getResourceById(id: bigint): Promise<Resource | null>;
    getResourcesByType(resourceType: string): Promise<Array<Resource>>;
    getRewards(): Promise<Array<Reward>>;
    getUsageDuration(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWellnessMetrics(): Promise<WellnessMetrics>;
    isCallerAdmin(): Promise<boolean>;
    isOnboardingCompleted(): Promise<boolean>;
    logMedicationAdherence(medicationId: bigint, taken: boolean, notes: string): Promise<void>;
    manageRewards(category: string, activityScore: bigint, reflectionScore: bigint, categoryScore: bigint, categoryDescription: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveQuizResponse(questionId: string, answer: string): Promise<void>;
    searchResources(searchTerm: string): Promise<Array<Resource>>;
    setUsageDuration(months: bigint): Promise<void>;
    updateDebt(debtId: bigint, creditorName: string, amount: bigint, interestRate: bigint, dueDate: Time, payments: Array<DebtPayment>, status: DebtStatus): Promise<void>;
    updateDebtStatus(debtId: bigint, newStatus: DebtStatus): Promise<void>;
    updateMedication(medicationId: bigint, name: string, dosage: string, frequency: string, timeOfDay: string, startDate: Time, endDate: Time | null): Promise<void>;
    updateResource(id: bigint, title: string, description: string, resourceType: string, link: string, resource: ExternalBlob): Promise<void>;
    updateWellnessPillar(pillarName: string, progress: bigint): Promise<void>;
    uploadProgressPhoto(photo: ExternalBlob, description: string, isBaseline: boolean): Promise<void>;
}
import type { Badge as _Badge, DebtPayment as _DebtPayment, DebtRecord as _DebtRecord, DebtStatus as _DebtStatus, ExternalBlob as _ExternalBlob, JournalEntry as _JournalEntry, MedicationAdherence as _MedicationAdherence, MedicationRecord as _MedicationRecord, MindfulnessActivity as _MindfulnessActivity, ProgressPhoto as _ProgressPhoto, QuizResponse as _QuizResponse, Resource as _Resource, Reward as _Reward, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WellnessMetrics as _WellnessMetrics, WellnessPillar as _WellnessPillar, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDebt(arg0: string, arg1: bigint, arg2: bigint, arg3: Time, arg4: Array<DebtPayment>, arg5: DebtStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDebt(arg0, arg1, arg2, arg3, arg4, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDebt(arg0, arg1, arg2, arg3, arg4, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addDebtPayment(arg0: bigint, arg1: DebtPayment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDebtPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDebtPayment(arg0, arg1);
            return result;
        }
    }
    async addJournalEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0);
            return result;
        }
    }
    async addMedication(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time, arg5: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addMindfulnessActivity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMindfulnessActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMindfulnessActivity(arg0, arg1);
            return result;
        }
    }
    async addResource(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeOnboarding(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOnboarding();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOnboarding();
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1);
            return result;
        }
    }
    async deleteDebt(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDebt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDebt(arg0);
            return result;
        }
    }
    async deleteMedication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedication(arg0);
            return result;
        }
    }
    async deleteResource(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResource(arg0);
            return result;
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserWellnessPillars(): Promise<Array<WellnessPillar>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserWellnessPillars();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserWellnessPillars();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBadges(): Promise<Array<Badge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBadges();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBadges();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBaselinePhoto(): Promise<ProgressPhoto | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBaselinePhoto();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBaselinePhoto();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebts(): Promise<Array<DebtRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowupPhoto(): Promise<ProgressPhoto | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowupPhoto();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowupPhoto();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedications(): Promise<Array<MedicationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedications();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedications();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoints(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoints();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoints();
            return result;
        }
    }
    async getProgressPhotos(): Promise<Array<ProgressPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressPhotos();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressPhotos();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourceById(arg0: bigint): Promise<Resource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourceById(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourceById(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesByType(arg0: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesByType(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesByType(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewards(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getUsageDuration(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsageDuration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsageDuration();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWellnessMetrics(): Promise<WellnessMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getWellnessMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWellnessMetrics();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOnboardingCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnboardingCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnboardingCompleted();
            return result;
        }
    }
    async logMedicationAdherence(arg0: bigint, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMedicationAdherence(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMedicationAdherence(arg0, arg1, arg2);
            return result;
        }
    }
    async manageRewards(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.manageRewards(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.manageRewards(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveQuizResponse(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResponse(arg0, arg1);
            return result;
        }
    }
    async searchResources(arg0: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResources(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResources(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUsageDuration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUsageDuration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUsageDuration(arg0);
            return result;
        }
    }
    async updateDebt(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: Time, arg5: Array<DebtPayment>, arg6: DebtStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDebt(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDebt(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateDebtStatus(arg0: bigint, arg1: DebtStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDebtStatus(arg0, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDebtStatus(arg0, to_candid_DebtStatus_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMedication(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Time, arg6: Time | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateResource(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResource(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateWellnessPillar(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWellnessPillar(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWellnessPillar(arg0, arg1);
            return result;
        }
    }
    async uploadProgressPhoto(arg0: ExternalBlob, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProgressPhoto(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProgressPhoto(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
}
function from_candid_Badge_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DebtRecord_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtRecord): DebtRecord {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_DebtStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtStatus): DebtStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MedicationRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicationRecord): MedicationRecord {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ProgressPhoto_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressPhoto): Promise<ProgressPhoto> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Resource_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Promise<Resource> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressPhoto]): Promise<ProgressPhoto | null> {
    return value.length === 0 ? null : await from_candid_ProgressPhoto_n34(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resource]): Promise<Resource | null> {
    return value.length === 0 ? null : await from_candid_Resource_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    resource: _ExternalBlob;
    link: string;
    description: string;
    resourceType: string;
}): Promise<{
    id: bigint;
    title: string;
    resource: ExternalBlob;
    link: string;
    description: string;
    resourceType: string;
}> {
    return {
        id: value.id,
        title: value.title,
        resource: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.resource),
        link: value.link,
        description: value.description,
        resourceType: value.resourceType
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    usageDurationMonths: bigint;
    quizResponses: Array<_QuizResponse>;
    username: string;
    journalEntries: Array<_JournalEntry>;
    badges: Array<_Badge>;
    wellnessPillars: Array<_WellnessPillar>;
    email: string;
    mindfulnessActivities: Array<_MindfulnessActivity>;
    medications: Array<_MedicationRecord>;
    onboardingCompleted: boolean;
    gamifiedScore: bigint;
    rewards: Array<_Reward>;
    skinHealthScore: bigint;
    debts: Array<_DebtRecord>;
    wellnessMetrics: _WellnessMetrics;
    points: bigint;
    progressPhotos: Array<_ProgressPhoto>;
}): Promise<{
    id: Principal;
    usageDurationMonths: bigint;
    quizResponses: Array<QuizResponse>;
    username: string;
    journalEntries: Array<JournalEntry>;
    badges: Array<Badge>;
    wellnessPillars: Array<WellnessPillar>;
    email: string;
    mindfulnessActivities: Array<MindfulnessActivity>;
    medications: Array<MedicationRecord>;
    onboardingCompleted: boolean;
    gamifiedScore: bigint;
    rewards: Array<Reward>;
    skinHealthScore: bigint;
    debts: Array<DebtRecord>;
    wellnessMetrics: WellnessMetrics;
    points: bigint;
    progressPhotos: Array<ProgressPhoto>;
}> {
    return {
        id: value.id,
        usageDurationMonths: value.usageDurationMonths,
        quizResponses: value.quizResponses,
        username: value.username,
        journalEntries: value.journalEntries,
        badges: from_candid_vec_n21(_uploadFile, _downloadFile, value.badges),
        wellnessPillars: value.wellnessPillars,
        email: value.email,
        mindfulnessActivities: value.mindfulnessActivities,
        medications: from_candid_vec_n25(_uploadFile, _downloadFile, value.medications),
        onboardingCompleted: value.onboardingCompleted,
        gamifiedScore: value.gamifiedScore,
        rewards: value.rewards,
        skinHealthScore: value.skinHealthScore,
        debts: from_candid_vec_n28(_uploadFile, _downloadFile, value.debts),
        wellnessMetrics: value.wellnessMetrics,
        points: value.points,
        progressPhotos: await from_candid_vec_n33(_uploadFile, _downloadFile, value.progressPhotos)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achieved: boolean;
    achievedTimestamp: [] | [_Time];
    name: string;
    pointsNeeded: bigint;
    description: string;
    progress: bigint;
}): {
    achieved: boolean;
    achievedTimestamp?: Time;
    name: string;
    pointsNeeded: bigint;
    description: string;
    progress: bigint;
} {
    return {
        achieved: value.achieved,
        achievedTimestamp: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.achievedTimestamp)),
        name: value.name,
        pointsNeeded: value.pointsNeeded,
        description: value.description,
        progress: value.progress
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate: [] | [_Time];
    dosage: string;
    name: string;
    adherenceLogs: Array<_MedicationAdherence>;
    frequency: string;
    timeOfDay: string;
    startDate: _Time;
}): {
    id: bigint;
    endDate?: Time;
    dosage: string;
    name: string;
    adherenceLogs: Array<MedicationAdherence>;
    frequency: string;
    timeOfDay: string;
    startDate: Time;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.endDate)),
        dosage: value.dosage,
        name: value.name,
        adherenceLogs: value.adherenceLogs,
        frequency: value.frequency,
        timeOfDay: value.timeOfDay,
        startDate: value.startDate
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DebtStatus;
    payments: Array<_DebtPayment>;
    dueDate: _Time;
    interestRate: bigint;
    creditorName: string;
    amount: bigint;
}): {
    id: bigint;
    status: DebtStatus;
    payments: Array<DebtPayment>;
    dueDate: Time;
    interestRate: bigint;
    creditorName: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_DebtStatus_n31(_uploadFile, _downloadFile, value.status),
        payments: value.payments,
        dueDate: value.dueDate,
        interestRate: value.interestRate,
        creditorName: value.creditorName,
        amount: value.amount
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    isBaseline: boolean;
    timestamp: _Time;
    photo: _ExternalBlob;
}): Promise<{
    description: string;
    isBaseline: boolean;
    timestamp: Time;
    photo: ExternalBlob;
}> {
    return {
        description: value.description,
        isBaseline: value.isBaseline,
        timestamp: value.timestamp,
        photo: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.photo)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    overdue: bigint;
} | {
    paidOff: null;
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "overdue";
    overdue: bigint;
} | {
    __kind__: "paidOff";
    paidOff: null;
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "overdue" in value ? {
        __kind__: "overdue",
        overdue: value.overdue
    } : "paidOff" in value ? {
        __kind__: "paidOff",
        paidOff: value.paidOff
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Promise<Array<Resource>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Resource_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicationRecord>): Array<MedicationRecord> {
    return value.map((x)=>from_candid_MedicationRecord_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DebtRecord>): Array<DebtRecord> {
    return value.map((x)=>from_candid_DebtRecord_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProgressPhoto>): Promise<Array<ProgressPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ProgressPhoto_n34(_uploadFile, _downloadFile, x)));
}
function to_candid_Badge_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Badge): _Badge {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_DebtRecord_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DebtRecord): _DebtRecord {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_DebtStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DebtStatus): _DebtStatus {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MedicationRecord_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicationRecord): _MedicationRecord {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function to_candid_ProgressPhoto_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgressPhoto): Promise<_ProgressPhoto> {
    return await to_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    usageDurationMonths: bigint;
    quizResponses: Array<QuizResponse>;
    username: string;
    journalEntries: Array<JournalEntry>;
    badges: Array<Badge>;
    wellnessPillars: Array<WellnessPillar>;
    email: string;
    mindfulnessActivities: Array<MindfulnessActivity>;
    medications: Array<MedicationRecord>;
    onboardingCompleted: boolean;
    gamifiedScore: bigint;
    rewards: Array<Reward>;
    skinHealthScore: bigint;
    debts: Array<DebtRecord>;
    wellnessMetrics: WellnessMetrics;
    points: bigint;
    progressPhotos: Array<ProgressPhoto>;
}): Promise<{
    id: Principal;
    usageDurationMonths: bigint;
    quizResponses: Array<_QuizResponse>;
    username: string;
    journalEntries: Array<_JournalEntry>;
    badges: Array<_Badge>;
    wellnessPillars: Array<_WellnessPillar>;
    email: string;
    mindfulnessActivities: Array<_MindfulnessActivity>;
    medications: Array<_MedicationRecord>;
    onboardingCompleted: boolean;
    gamifiedScore: bigint;
    rewards: Array<_Reward>;
    skinHealthScore: bigint;
    debts: Array<_DebtRecord>;
    wellnessMetrics: _WellnessMetrics;
    points: bigint;
    progressPhotos: Array<_ProgressPhoto>;
}> {
    return {
        id: value.id,
        usageDurationMonths: value.usageDurationMonths,
        quizResponses: value.quizResponses,
        username: value.username,
        journalEntries: value.journalEntries,
        badges: to_candid_vec_n43(_uploadFile, _downloadFile, value.badges),
        wellnessPillars: value.wellnessPillars,
        email: value.email,
        mindfulnessActivities: value.mindfulnessActivities,
        medications: to_candid_vec_n46(_uploadFile, _downloadFile, value.medications),
        onboardingCompleted: value.onboardingCompleted,
        gamifiedScore: value.gamifiedScore,
        rewards: value.rewards,
        skinHealthScore: value.skinHealthScore,
        debts: to_candid_vec_n49(_uploadFile, _downloadFile, value.debts),
        wellnessMetrics: value.wellnessMetrics,
        points: value.points,
        progressPhotos: await to_candid_vec_n52(_uploadFile, _downloadFile, value.progressPhotos)
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achieved: boolean;
    achievedTimestamp?: Time;
    name: string;
    pointsNeeded: bigint;
    description: string;
    progress: bigint;
}): {
    achieved: boolean;
    achievedTimestamp: [] | [_Time];
    name: string;
    pointsNeeded: bigint;
    description: string;
    progress: bigint;
} {
    return {
        achieved: value.achieved,
        achievedTimestamp: value.achievedTimestamp ? candid_some(value.achievedTimestamp) : candid_none(),
        name: value.name,
        pointsNeeded: value.pointsNeeded,
        description: value.description,
        progress: value.progress
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    endDate?: Time;
    dosage: string;
    name: string;
    adherenceLogs: Array<MedicationAdherence>;
    frequency: string;
    timeOfDay: string;
    startDate: Time;
}): {
    id: bigint;
    endDate: [] | [_Time];
    dosage: string;
    name: string;
    adherenceLogs: Array<_MedicationAdherence>;
    frequency: string;
    timeOfDay: string;
    startDate: _Time;
} {
    return {
        id: value.id,
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        dosage: value.dosage,
        name: value.name,
        adherenceLogs: value.adherenceLogs,
        frequency: value.frequency,
        timeOfDay: value.timeOfDay,
        startDate: value.startDate
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: DebtStatus;
    payments: Array<DebtPayment>;
    dueDate: Time;
    interestRate: bigint;
    creditorName: string;
    amount: bigint;
}): {
    id: bigint;
    status: _DebtStatus;
    payments: Array<_DebtPayment>;
    dueDate: _Time;
    interestRate: bigint;
    creditorName: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: to_candid_DebtStatus_n8(_uploadFile, _downloadFile, value.status),
        payments: value.payments,
        dueDate: value.dueDate,
        interestRate: value.interestRate,
        creditorName: value.creditorName,
        amount: value.amount
    };
}
async function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    isBaseline: boolean;
    timestamp: Time;
    photo: ExternalBlob;
}): Promise<{
    description: string;
    isBaseline: boolean;
    timestamp: _Time;
    photo: _ExternalBlob;
}> {
    return {
        description: value.description,
        isBaseline: value.isBaseline,
        timestamp: value.timestamp,
        photo: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photo)
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "active";
    active: null;
} | {
    __kind__: "overdue";
    overdue: bigint;
} | {
    __kind__: "paidOff";
    paidOff: null;
}): {
    active: null;
} | {
    overdue: bigint;
} | {
    paidOff: null;
} {
    return value.__kind__ === "active" ? {
        active: value.active
    } : value.__kind__ === "overdue" ? {
        overdue: value.overdue
    } : value.__kind__ === "paidOff" ? {
        paidOff: value.paidOff
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Badge>): Array<_Badge> {
    return value.map((x)=>to_candid_Badge_n44(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MedicationRecord>): Array<_MedicationRecord> {
    return value.map((x)=>to_candid_MedicationRecord_n47(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DebtRecord>): Array<_DebtRecord> {
    return value.map((x)=>to_candid_DebtRecord_n50(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProgressPhoto>): Promise<Array<_ProgressPhoto>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ProgressPhoto_n53(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
